# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57e203a9e55432002a6594daa5cd7db165fa516340bc6a9f9edbcd6dfe287f7301b4c57077d796ff560e5a6fccb2fafc510d7c9261d62d7b8b78099b0fb58ffc

test:
  secret_key_base: 375123ae4792f5beb9cb371462caa0257aa6b0a6698b6cdc2e6df7f93606151a50145db4841c3e187ef8b908511d7c10bb80d3dac7b848ac5af083aaca6e7159

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
